# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='range',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
