# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170411_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='numbers_in_subset',
            field=models.IntegerField(blank=True, default=4),
            preserve_default=False,
        ),
    ]
