# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_document_numbers_in_subset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='numbers_in_subset',
        ),
    ]
